name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.3
          - 8.2
          - 8.1
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-file: development
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "mariadb-10.11"
          root-password: "root"

      - run: mysql -e "CREATE DATABASE IF NOT EXISTS test_db;" -uroot -proot
      - run: echo -e "BS_DB_HOST=localhost\nBS_DB_PORT=3306\nBS_DB_USER=root\nBS_DB_PASS=root\nBS_DB_DBNAME=test_db\n" > .env
      - run: cat .env
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
